### ISSUE TITLE
Could Buffering be optional? 

### ISSUE THREAD

**Issue by JonathanHuot** [omrikiei/aws_logging_handlers#7]
Writing to a buffer is cool and nice, however sometime we want to write into Kinesis the quickest way as possible.

For instance, if we write `crit` and those are plugged into a `Kinesis` stream to be shown in a operator's dashboard, we may don't want to wait.

Any ideas about that ? 

Solutions that I have in mind: 
1) disable buffering per handler
2) disable buffering per severity
3) have a maximum delay where a buffer should be flushed (e.g. every 200ms the buffer is flushed if no new messages are added)

**Comment by omrikiei** [comment]
I think it would be good to implement option 3 regardless(it's better for time based rotations in general instead of waiting for input) on both handlers - maybe user scheduler.enterabs
And I will also consider implementing non-buffered streaming(need to test the effect on external performance) on demand per handler(it's easier and makes more sense to split log records by severity) @JonathanHuot would you want to take this task upon yourself? if not I will try to make time and sort this in the next couple of weeks

**Comment by omrikiei** [comment]
@JonathanHuot, 
Technically, you can setup a multiple handlers with different debug levels, and you can set a different buffer size(0 would flush every time - which will disable buffering) to achieve this versatility.
Closing the issue
